// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.0 DO NOT EDIT.
package api

import (
	"time"
)

// Links defines model for Links.
type Links = []string

// SetOfLinks defines model for SetOfLinks.
type SetOfLinks struct {
	Links *Links `json:"links,omitempty"`
}

// Task defines model for Task.
type Task struct {
	Created *time.Time `json:"created,omitempty"`
	Id      *string    `json:"id,omitempty"`
	Links   *Links     `json:"links,omitempty"`
}

// SetOfLinksJSONRequestBody defines body for SetOfLinks for application/json ContentType.
type SetOfLinksJSONRequestBody = SetOfLinks
