app:
  # APP_NAME - название приложения
  APP_NAME: "archive-files" 
  # APP_VERSION - версия приложения
  APP_VERSION: 1
  # APP_NUM_LINKS - максимальное количесво ссылок для скачивания в запросе 
  APP_NUM_LINKS: 3
  # APP_TASK_COUNT - число активных тасок
  APP_TASK_COUNT: 3
  # APP_CONTENT_TYPE - разрешенный формат файлов
  APP_CONTENT_TYPE: "application/pdf,image/jpeg"
  # APP_MAX_BYTES_RESP - ограничение размера скачиваемого файла
  # APP_MAX_BYTES_RESP: 51200
  APP_MAX_BYTES_RESP: 10485760
http:
  # HTTP_PORT - порт для запуска приложения
  HTTP_PORT: ":8080"

log:
  # LOG_LEVEL - уровень логирования
  LOG_LEVEL: debug

swagger:
  # SWAGGER_ENABLED - включение сваггера
  SWAGGER_ENABLED: true
 
 